version: "3.8"

services:
  django-mglobal-test-backend:
    container_name: "DjangoMGlobalTestBackend"
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/EmployeeData:/home/desarrollo/EmployeeData
    env_file:
      - envsThatShouldNotBeInRepo/dev_backend.env
    shm_size: "256mb" # Increase Shared Memory that is by default 64
    sysctls:
      - net.core.somaxconn=1024 # Increase the quantity og conections by default in 128
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:8000"